sudo: required
services:
  - docker
matrix:
  include:
    - env:
        - MAGENTO_VERSION=~2.2
        - TEST_SUITE=unit
    - env:
        - MAGENTO_VERSION=~2.2
        - TEST_SUITE=integration
    - env:
        - MAGENTO_VERSION=~2.2
        - TEST_SUITE=acceptance
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - echo "COMPOSER_MAGENTO_USERNAME=$COMPOSER_MAGENTO_USERNAME" >> dev/composer.env
  - echo "COMPOSER_MAGENTO_PASSWORD=$COMPOSER_MAGENTO_PASSWORD" >> dev/composer.env
  - echo "COMPOSER_GITHUB_TOKEN=$COMPOSER_GITHUB_TOKEN" >> dev/composer.env
  - sed -E -i "s/MAGENTO_VERSION=.*/MAGENTO_VERSION=${MAGENTO_VERSION}/" dev/docker-compose.yml
  - docker-compose -f dev/docker-compose.yml build
  - docker-compose -f dev/docker-compose.yml up -d
  - docker-compose -f dev/docker-compose.yml exec app module-installer
script:
  - docker-compose -f dev/docker-compose.yml exec app test-${TEST_SUITE}
